version: '3.1'

services:

  library_management:
    image: jishnujish/library_management:2024
    container_name: library_management
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database-1.c3y6k0ikg1wk.eu-north-1.rds.amazonaws.com:3306/library_management
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: springboot123
    networks:
      - default

#     Add other microservices here

networks:
  default:
    driver: bridge
