#server properties
server:
  port: 8080

#Datasource properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library_management
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "@springboot123"
#   com.mysql.cj.jdbc.Driver

  #jpa properties
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
#  cloud:
#    config:
#      enabled: false
#
#    #  main:
#    #    web-application-type: none
#
#    gateway:
#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods: "*"
#            allowedHeaders: "*"

logging:
  level:
    org.springframework.security: DEBUG